### ISSUE TITLE
The cookie still works, but why is there an error that the file cannot be found, and the file is moved to the broken folder?

### ISSUE THREAD

**Issue by NhatAnhDN** [ilyassesalama/Netflix-Cookies-Checker#1]
I went into the broken folder and checked netflix manually and found that the cookies were still active
But why does it not find the file and move it to the hits folder, but instead moves it to broken , I named the file very simply 
Log here > Login successful with cookies/na13.txt | Country: DE, Member since: Januar 2022, Extra members: False, Max Streams: 2}.
> Login successful with cookies/na14.txt | Country: GB, Member since: January 2021, Extra members: False, Max Streams: 4}.
> Error with cookies/na13.txt: [Errno 2] No such file or directory: 'cookies/na13.txt'
> Error with cookies/na14.txt: [Errno 2] No such file or directory: 'cookies/na14.txt'
[
![Screenshot_20240624-151549](https://github.com/ilyassesalama/Netflix-Cookies-Checker/assets/150426800/852b7006-14bb-495f-bf0b-ce375ad36d5a)
![Screenshot_20240624-151538](https://github.com/ilyassesalama/Netflix-Cookies-Checker/assets/150426800/c774ca1e-88cf-4e70-a4a3-fe41d31db6a8)

**Comment by ilyassesalama** [comment]
Hi, thanks for trying the script. It'd be nice if you share the cookies you have tried so I can try reproducing the issue to fix it. If you're not okay with sharing them publicly, send me a message on [Telegram](https://t.me/ilyassesalama).
